export const TASKS_GET = "TASKS_GET";
export const TASKS_GET_SUCCESS = "TASKS_GET_SUCCESS";
export const TASKS_GET_ERROR = "TASKS_GET_ERROR";

export const TASK_GET = "TASK_GET";
export const TASK_GET_SUCCESS = "TASK_GET_SUCCESS";
export const TASK_GET_ERROR = "TASK_GET_ERROR";

export const TASK_CREATE = "TASK_CREATE";
export const TASK_CREATE_SUCCESS = "TASK_CREATE_SUCCESS";
export const TASK_CREATE_ERROR = "TASK_CREATE_ERROR";

export const TASK_UPDATE = "TASK_UPDATE";
export const TASK_UPDATE_SUCCESS = "TASK_UPDATE_SUCCESS";
export const TASK_UPDATE_ERROR = "TASK_UPDATE_ERROR";

export const TASK_DELETE = "TASK_DELETE";
export const TASK_DELETE_SUCCESS = "TASK_DELETE_SUCCESS";
export const TASK_DELETE_ERROR = "TASK_DELETE_ERROR";

export const PRIORITIES_GET = "PRIORITIES_GET";
export const PRIORITIES_GET_SUCCESS = "PRIORITIES_GET_SUCCESS";
export const ALL_PRIORITIES_RESET = "ALL_PRIORITIES_RESET";
export const ALL_PRIORITIES_GET_SUCCESS = "ALL_PRIORITIES_GET_SUCCESS";
export const PRIORITIES_GET_ERROR = "PRIORITIES_GET_ERROR";

export const STATUSES_GET = "STATUSES_GET";
export const STATUSES_GET_SUCCESS = "STATUSES_GET_SUCCESS";
export const STATUSES_GET_ERROR = "STATUSES_GET_ERROR";

export const GET_BOARDS = "GET_BOARDS";
export const GET_BOARD = "GET_BOARD";
export const ADD_BOARD = "ADD_BOARD";
export const BOARD_ERROR = "BOARD_ERROR";
export const CLEAR_BOARD = "CLEAR_BOARD";

export const ADD_MEMBER_CLEAR = "ADD_MEMBER_CLEAR";
export const ADD_MEMBER_SUCCESS = "ADD_MEMBER_SUCCESS";
export const ADD_MEMBER_ERROR = "ADD_MEMBER_ERROR";

export const CLEAR_TASKS = "CLEAR_TASKS";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";
